# Generated by Django 3.0.5 on 2020-05-12 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20200510_0129'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Name',
        ),
    ]
